version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: quotes-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B2k25ismine@1$
      POSTGRES_DB: quotes_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
